Resources:
 myOS:
  Type: AWS::EC2::Instance
  Properties:
   AvailabilityZone: ap-south-1a
   ImageId: ami-0ad704c126371a549
   InstanceType: t2.micro
   KeyName: arth_aws
   Tags:
   - Key: Name
     Value: osForTask
 
 ebsVolume:
  Type: AWS::EC2::Volume
  Properties: 
   AvailabilityZone: ap-south-1a
   Size: 5
   Tags:
   - Key: Name
     Value: volumeForTask

 volumeAttachment:
  Type: AWS::EC2::VolumeAttachment
  Properties: 
   Device: /dev/sdh
   InstanceId: !Ref myOS
   VolumeId: !Ref ebsVolume
